In [1]:
import numpy as np

# 1. Write a Python Program to Add Two Matrices?

In [3]:
a = np.random.randint(10, size=(3,3))
b = np.random.randint(10, size=(3,3))
a+b

array([[ 7,  3,  9],
       [ 6, 13,  9],
       [ 3,  3,  9]])

# 2. Write a Python Program to Multiply Two Matrices?

In [9]:
c = np.random.randint(10, size=(3,3))
d = np.random.randint(10, size=(3,3))
np.dot(c,d)

array([[ 70,  32,  70],
       [105,  61, 151],
       [ 49,  59, 135]])

# 3. Write a Python Program to Transpose a Matrix?

In [14]:
e = np.random.randint(10, size=(3,3))
e.T

array([[3, 8, 9],
       [7, 3, 6],
       [1, 2, 7]])

# 4. Write a Python Program to Sort Words in Alphabetic Order?

In [20]:
f = 'anuj'
''.join(sorted(f))

'ajnu'

# 5. Write a Python Program to Remove Punctuation From a String?

In [24]:
punct = ('.', '?', '!', ',', ':', ';', '-', '[', ']', '{', '}', '(', ')', "'", '"')

def rem_punct(s):
    out = ''
    for char in s:
        if char not in punct:
            out += char
    return out